Improve query assertion message for mismatched types
Compare column types before looking at row mismatches to help with
debugging failures where the columns display the same but are actually
different types (e.g. float vs. double or bigint vs. int)

Previous failure message for mismatched bigint vs. int type:
java.lang.AssertionError: For query:
 SELECT array_position(simple_double_array, nan()) FROM array_nans_table
not equal
Actual rows (6 of 6 extra rows shown, 7 rows in total):
    [1]
    [1]
    [2]
    [2]
    [4]
    [3]
Expected rows (6 of 6 missing rows shown, 7 rows in total):
    [1]
    [1]
    [2]
    [2]
    [4]
    [3]

New failure message:
java.lang.AssertionError: For query:
 SELECT array_position(simple_double_array, nan()) FROM array_nans_table
Actual and expected types do not match: Lists differ at element [0]: integer != bigint
Expected :integer
Actual   :bigint